### ISSUE TITLE
Create a flow-chart using draw.io to depict the UI and color changes

### ISSUE THREAD

**Issue by abhishkpram** [abhishkpram/house-water-motor-ai#2]
Create a flow-chart for the House-water-motor-ai with colour changes depicted correctly.

**Comment by aarshps** [comment]
@abhishkpram please attach the flow-diagram made into this issue for review.

**Comment by aarshps** [comment]
@abhishkpram please fill assignee and description appropriately.

**Comment by abhishkpram** [comment]
@aarshps please review.

https://github.com/abhishkpram/house-water-motor-ai/pull/3

**Comment by aarshps** [comment]
Looks good! 👍
